env: dev
app_dir: /home/{{ user }}/conduit-app
project_dir: /home/{{ vault_user }}
log_dir: /var/log/conduit-app
repo_url: https://github.com/Rob-in-son/conduit-app.git
repo_name: conduit-app

# Database configuration
db_dialect: postgres
db_hostname: 127.0.0.1