---
- name: Deploy conduit app
  hosts: conduit-tf
  become: yes
  vars_files:
    - vars/main.yml
    - vars/vault.yml
    - "vars/env_{{ env }}.yml"

  tasks:
    - name: Update apt cache
      apt: update_cache=yes

    - name: Install base dependencies
      apt:
        name: 
          - git 
          - npm
          - postgresql
          - nginx
        state: present
    
    - name: Install Node.js
      shell: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
        nvm install 20
        nvm use 20

    - name: Clone github repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ project_dir }}"
        clone: yes
        update: yes

    - name: Install project dependencies
      npm:
      path: "{{ app_dir }}"
      become: yes

    - name: Create .env file
      copy:
        content: |
          PORT= {{ vault_ports }}
          JWT_KEY={{ vault_jwt_key }}

          ## Development Database
          DEV_DB_USERNAME={{ vault_dev_db_username }}
          DEV_DB_PASSWORD={{ vault_dev_db_password }}
          DEV_DB_NAME={{ vault_dev_db_name }}
          DEV_DB_HOSTNAME={{ db_hostname }}
          DEV_DB_DIALECT={{ db_dialect }}
          DEV_DB_LOGGING=true
        dest: "{{ app_dir }}/.env"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0600'
      notify: Restart application

    - name: Create database using Sequelize CLI
      npm:
        command: run
        args: "sqlz -- db:create"
        path: "{{ app_dir }}"

    - name: Populate database with dummy data
      npm:
        command: run
        args: "sqlz -- db:seed:all"
        path: "{{ app_dir }}"

    # - name: Remove default Nginx configuration
    #   file:
    #     path: /etc/nginx/conf.d/default.conf
    #     state: absent

    # # Create nginx.conf.j2 template
    # - name: Set up custom Nginx configuration
    #   template:
    #     # src: conduit.conf
    #     dest: /etc/nginx/conf.d/conduit.conf
    #     mode: '0644'
    #     owner: root
    #     group: root
    #   notify: Restart Nginx

    - name: Debug environment
      debug:
        msg: "Running in {{ environment }} environment"